### ISSUE TITLE
1.15.2 not working

### ISSUE THREAD

**Issue by The-Mr-Mango** [Naxanria/itemgot#6]
It's not showing up in the mod menu. It does not work, unfortunately

**Comment by Naxanria** [comment]
Can you be a bit more specific? What version? What version of forge?

**Comment by The-Mr-Mango** [comment]
Oh wait, is it for Forge? Sorry, thought it was for Fabrix. nvm then

**Comment by The-Mr-Mango** [comment]
Cool mod nonetheless. Is updating it for Fabric an option ;)

**Comment by Naxanria** [comment]
Currently focusing on forge for all my mods.
